#### In NumPy, an array is a data structure that stores values of the same type in a grid-like format. It's similar to a list in Python but offers more efficiency for numerical operations. You can think of it as a collection of elements arranged in rows and columns (for 2D arrays) or in higher dimensions (e.g., 3D arrays). NumPy arrays, also known as ndarray, allow for efficient mathematical operations on large datasets and support multi-dimensional arrays.

In [2]:
import numpy as np

## 1D Array  

In [27]:
List = [1, 2, 3, 4, 5, 6]  # Creating a Python list
print(List, type(List))  # Printing the list and its type (It will be of type 'list')

List = np.array(List)  # Converting the list into a NumPy array
print(List, type(List))  # Printing the NumPy array and its type (It will be of type 'ndarray')

np.ndim(List) # Return the dimenson in the array


[1, 2, 3, 4, 5, 6] <class 'list'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


1

## 2D Array

In [29]:
List2d = [[1, 2, 3], 
          [4, 5, 6]]  # Creating a 2D Python list (list of lists)
print(List2d, type(List2d))  # Printing the 2D list and its type (It will be of type 'list')

List2d = np.array(List2d)  # Converting the 2D list into a NumPy 2D array
print(List2d, type(List2d))  # Printing the NumPy 2D array and its type (It will be of type 'ndarray')

np.ndim(List2d) # Return the dimenson in the array

[[1, 2, 3], [4, 5, 6]] <class 'list'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


2

## 3D Array

In [68]:
List3d=[[[1,2,3]],[[4,5,6]]]
print(List3d,type(List3d))

List3d=np.array(List3d)
print(List3d,type(List3d))

np.ndim(List3d) # Return the dimenson in the array



[[[1, 2, 3]], [[4, 5, 6]]] <class 'list'>
[[[1 2 3]]

 [[4 5 6]]] <class 'numpy.ndarray'>


3

## Knowing your array these are the 3 basic commands for knowing the quality of your array

In [84]:
# Knowing your array these are the 3 basic commands for knowing the quality of your array
import numpy as np  # Importing the NumPy library as np

List2d = [[1, 2, 3], 
          [4, 5, 6]]  # Creating a 2D Python list (list of lists)

List2d = np.array(List2d)  # Converting the list into a NumPy array

# 1. np.ndim(List2d): Returns the number of dimensions of the array
print("Number of dimensions (ndim):", np.ndim(List2d))  # Output will be 2 (as it's a 2D array)

# 2. np.size(List2d): Returns the total number of elements in the array
print("Total number of elements (size):", np.size(List2d))  # Output will be 6 (as there are 6 elements)

# 3. np.shape(List2d): Returns the shape of the array (number of rows, number of columns)
print("Shape of the array (shape):", np.shape(List2d))  # Output will be (2, 3) as it has 2 rows and 3 columns

# List2d.itemsize: Returns the size (in bytes) of each element of the array
print("Size of each element (itemsize):", List2d.itemsize)  # Output will be 8 (for an int64 array)

# List2d.size: Returns the total number of elements in the array (same as np.size)
print("Total number of elements (size):", List2d.size)  # Output will be 6

# List2d: Printing the array itself
print("Array contents:", List2d)  # Output will be the array itself: [[1 2 3] [4 5 6]]

# List2d.dtype: Returns the data type of the elements in the array
print("Data type of the elements (dtype):", List2d.dtype)  # Output will be 'int64' (or 'int32' depending on the system)


Number of dimensions (ndim): 2
Total number of elements (size): 6
Shape of the array (shape): (2, 3)
Size of each element (itemsize): 4
Total number of elements (size): 6
Array contents: [[1 2 3]
 [4 5 6]]
Data type of the elements (dtype): int32


In [41]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [43]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## When you need to create randon array witth diffrent qualities for parctice purpose


In [50]:
# Creating a NumPy array using np.arange() with values from 1 to 19 (step of 2)
arr1 = np.arange(1, 20, 2)  
print(arr1)  # Output will be: [ 1  3  5  7  9 11 13 15 17 19]

# Reshaping the array into a 2x5 matrix (2 rows, 5 columns)
arr1_reshaped = arr1.reshape(2, 5)  
print(arr1_reshaped)  # Output will be a 2D array:
# [[ 1  3  5  7  9]
#  [11 13 15 17 19]]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [54]:
# Generating an array of random integers between 2 (inclusive) and 5 (exclusive)
arr = np.random.randint(2, 5, 2)  
print(arr)  # Printing the generated array


array([3, 4])

In [58]:
import numpy as np  # Importing the NumPy library

# Generating an array of 10 evenly spaced values between 2 and 100 (inclusive)
arr = np.linspace(2, 100, num=10)  
print(arr)  # Printing the generated array


[  2.          12.88888889  23.77777778  34.66666667  45.55555556
  56.44444444  67.33333333  78.22222222  89.11111111 100.        ]


In [62]:
import numpy as np  # Importing the NumPy library

# Creating a 2x3 array filled with the value 88
arr = np.full((2, 3), 88)  
print(arr)  # Printing the generated array


array([[88, 88, 88],
       [88, 88, 88]])

## Additional Note:
You can use np.full() to create arrays similar to those created with np.zeros() or np.ones() but with any value you choose. For example:
np.zeros((2, 3),0) creates a 2x3 array filled with zeros.
np.ones((2, 3),1) creates a 2x3 array filled with ones.
np.full((2, 3), 7) creates a 2x3 array filled with the value 7.
Using np.full() is versatile because it allows you to fill the array with any constant value, not just zeros or ones.

## When you want to chage the qualities of an exisiting array theese are the few functions in Numpy


In [91]:
import numpy as np  # Importing NumPy library
#Transposes the array, swapping rows and columns. For multidimensional arrays, it reverses the order of axes.
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Creating a 2D array
transposed_arr = arr.transpose()  # Transposing the array
print("Transposed array:\n", transposed_arr)



Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


In [93]:
# Reshapes the array to a new shape without changing its data.
arr = np.array([1, 2, 3, 4, 5, 6])  # Creating a 1D array
reshaped_arr = arr.reshape(2, 3)  # Reshaping to 2 rows and 3 columns
print("Reshaped array:\n", reshaped_arr)


Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [95]:
#Converts the array to a different data type.
arr = np.array([1.5, 2.5, 3.5])  # Creating an array of floats
int_arr = arr.astype(int)  # Converting to integers
print("Array with integer type:\n", int_arr)


Array with integer type:
 [1 2 3]


In [101]:
#Stacks arrays horizontally (column-wise).
arr1 = np.array([[1], [2]])  # Creating the first array
arr2 = np.array([[3], [4]])  # Creating the second array
hstack_arr = np.hstack((arr1, arr2))  # Horizontally stacking the arrays
print("Horizontally stacked array:\n", hstack_arr)

Horizontally stacked array:
 [[1 3]
 [2 4]]


In [103]:
#Stacks arrays vertically (row-wise).
arr1 = np.array([[1, 2, 3]])  # Creating the first array
arr2 = np.array([[4, 5, 6]])  # Creating the second array
vstack_arr = np.vstack((arr1, arr2))  # Vertically stacking the arrays
print("Vertically stacked array:\n", vstack_arr)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]]


In [105]:
#Flattens a multi-dimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Creating a 2D array
flattened_arr = arr.ravel()  # Flattening to a 1D array
print("Flattened array:\n", flattened_arr)


Flattened array:
 [1 2 3 4 5 6]


In [107]:
#Splits an array into multiple sub-arrays vertically (row-wise).
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Creating a 2D array
vsplit_arr = np.vsplit(arr, 3)  # Splitting into 3 sub-arrays
print("Vertically split arrays:")
for sub_arr in vsplit_arr:
    print(sub_arr)

Vertically split arrays:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [109]:
# Splits an array into multiple sub-arrays horizontally (column-wise).
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # Creating a 2D array
hsplit_arr = np.hsplit(arr, 2)  # Splitting into 2 sub-arrays
print("Horizontally split arrays:")
for sub_arr in hsplit_arr:
    print(sub_arr)

Horizontally split arrays:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [112]:
# Returns a copy of the array collapsed into one dimension.
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Creating a 2D array
flattened_arr = arr.flatten()  # Flattening to a 1D array
print("Flattened array:\n", flattened_arr)


Flattened array:
 [1 2 3 4 5 6]


In [114]:
# Repeats elements of an array along a specified axis
arr = np.array([[1, 2], [3, 4]])  # Creating a 2x2 array
arr.resize((3, 3))  # Resizing to 3x3 array
print("Resized array:\n", arr)

Resized array:
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


In [116]:
# Constructs an array by repeating the input array a specified number of times.
arr = np.array([1, 2, 3])  # Creating a 1D array
tiled_arr = np.tile(arr, 3)  # Repeating the array 3 times
print("Tiled array:\n", tiled_arr)

Tiled array:
 [1 2 3 1 2 3 1 2 3]


In [118]:
# Sorts the array along a specified axis. This is done in-place, meaning it modifies the original array.
arr = np.array([[3, 1, 2], [6, 4, 5]])  # Creating a 2D array
arr.sort(axis=1)  # Sorting each row
print("Sorted array:\n", arr)

Sorted array:
 [[1 2 3]
 [4 5 6]]


In [122]:
# Returns the indices that would sort an array.
arr22 = np.array([3, 1, 2])  # Creating a 1D array
sorted_indices = np.argsort(arr22)  # Getting the indices that would sort the array
print("Sorted indices:\n", sorted_indices)

Sorted indices:
 [1 2 0]


In [124]:
# Finds the unique elements of an array and can return them in sorted order.
arr = np.array([1, 2, 2, 3, 3, 3])  # Creating an array with duplicate values
unique_arr = np.unique(arr)  # Finding unique elements
print("Unique elements:\n", unique_arr)


Unique elements:
 [1 2 3]


In [126]:
# Limits the values in an array to a specified range.
arr = np.array([1, 5, 10, 15])  # Creating an array
clipped_arr = np.clip(arr, 3, 12)  # Clipping values to be between 3 and 12
print("Clipped array:\n", clipped_arr)

Clipped array:
 [ 3  5 10 12]


## Numpy Operations


In [129]:
Array=np.arange(1,20,2)

In [141]:
np.size(Array)
np.ndim(Array)
np.shape(Array)


(10,)

In [197]:
Array2=np.random.randint(1,10,8)
np.size(Array2)
Array2

array([9, 8, 9, 7, 9, 8, 2, 6])

In [201]:
Array2d=Array2.reshape(2,4)
Array2d

array([[9, 8, 9, 7],
       [9, 8, 2, 6]])

In [207]:
#Max or Min
# axis=0: Refers to the direction along the rows of a 2D array. It operates vertically downwards along columns.
# axis=1: Refers to the direction along the columns of a 2D array. It operates horizontally across rows.
np.max(Array2d,axis=0) #Maximum number in each column

array([9, 8, 9, 7])

In [213]:
#Sum Operation along the axes

np.sum(Array2d,axis=0)


# Some of the other functons are :-

# mean,median,mode,std,exp

array([18, 16, 11, 13])

## Indexing and Slicing in Numpy arrays

### Extract a Subarray

#### Question: How would you extract the subarray consisting of the first 2 rows and the first 3 columns from Array2d?
#####Answer: Array2d[:2, :3]

In [219]:
Array2d

array([[9, 8, 9, 7],
       [9, 8, 2, 6]])

In [226]:
Array2d[0:2,0:3]

array([[9, 8, 9],
       [9, 8, 2]])

### Access Specific Elements

#### Question: What is the result of accessing the element in the second row and third column of Array2d?
##### Answer: Array2d[1, 2]

In [229]:
Array2d[1,2]

2

### Slice a 1D Array

#### Question: How can you get the last 4 elements from Array2?
##### Answer: Array2[-4:]

In [232]:
Array2[-4:]

array([9, 8, 2, 6])

### Change Values Using Slicing

#### Question: How can you set all values in the second row of Array2d to 99?
#### Answer: Array2d[1, :] = 99

In [235]:
Array2d[1,:]=99
Array2d

array([[ 9,  8,  9,  7],
       [99, 99, 99, 99]])

### Slicing with Step Size

#### Question: How would you get every second element from Array2?
##### Answer: Array2[::2]

In [246]:
 Array2[::2]

array([ 9,  9, 99, 99])

In [248]:
Array2

array([ 9,  8,  9,  7, 99, 99, 99, 99])

In [255]:
Array2d[Array2d>5]

array([ 9,  8,  9,  7, 99, 99, 99, 99])